<?php

$questionnaires = [
    "Department of study at Accra Technical University (ATU)",
    "Year of Entry ",
    "Mode of Entry ",
    "Year of Completion",
    "Session of Study",
    "Programme of study at ATU",
    "Primary reason for choosing ATU",
    "Primary reason for choosing programme",
    "Highest qualification obtained at ATU ",
    "Did you undertake any industrial attachment(s) while at ATU? ",
    "Name the organisation(s) of industrial attachment ",
    "Duration of industrial attachment(s)",
    "Was/were your industrial attachment(s) relevant to your course of study at ATU? ",
    "How relevant was/were your industrial attachment(s)?",
    "If 'No', please provide reason(s) for your inability to undertake an industrial attachment ",
    "Current status/nature of employment ",
    "When did you start searching for a job? Whiles in ATU? ",
    "How long did it take to secure your first job after graduating from ATU? ",
    "What was the most successful method for finding your first job? ",
    "How do you perceive the following competencies/skills as affecting recruitment? ",
    "To what extent did you acquire the following competencies/skills at ATU? ",
    "To what extent do you agree or disagree that the knowledge and skills acquired at ATU are utilised in your current job?",
    "To which sector does your current employment belong?",
    "Job title/position of current employment ",
    "To what extent would you choose the same field of study, if you were to decide again?",
    "To what extent are you satisfied with your studies at ATU? ",
    "To what extent would you choose ATU, if you were to decide again? ",
    "Are you an active member of ATU Alumni? ",
    "If 'No', would you like to join? ",
    "Please provide other relevant feedback to ATU for quality assurance purposes. ",
    "Please provide the contact information of alumni within your reach to extend participation in the study.",
    
];
